### ISSUE TITLE
Android: MarkerView moves during resizing map 

### ISSUE THREAD

**Issue by bigoloo** [mapbox/mapbox-plugins-android#1002]
I am using  `MarkerView` and add it to my map but my  problem is whenever I move map or change zoom ,inflated view (`MarkerView`) is moving.

PS : 
mapbox-android-sdk version is  8.1.0
mapbox-android-plugin-markerview-v8 version is 0.3.0

**Comment by philoez98** [comment]
I have this problem too. The `MarkerView` doesn't seem to be anchored to its LatLng point.

**Comment by langsmith** [comment]
Hi @bigoloo and @philoez98 , thanks for using Mapbox! The `MarkerView` is a bit laggy and not solidly anchored to its coordinate because it's an Android-system `View`. The `View` has to be redrawn whenever the map moves. When the map is moved quickly and redrawing has to happen often, this is an expense procedure, which leads to that visual lag that both of you are reporting.

If you don't want this lag, I'd highly recommend you look into using `SymbolLayer`s to show your icons. You can use `SymbolLayer`s directly or use [the Mapbox Annotation Plugin for Android](https://docs.mapbox.com/android/plugins/overview/annotation/).

- https://docs.mapbox.com/android/maps/overview/annotations/
- https://docs.mapbox.com/android/maps/overview/data-driven-styling/#symbol
- https://docs.mapbox.com/android/maps/examples/marker-symbol-layer/
- https://docs.mapbox.com/android/maps/examples/symbol-layer-info-window/
- https://github.com/mapbox/mapbox-android-demo/search?l=Java&q=SymbolLayer

**Comment by philoez98** [comment]
@langsmith thanks for the explanation. But still, to my understanding, using `SymboLayer` directly or through the plugin doesn't allow to use custom views as icons. In my case I was using a `MarkerView` only as an Info-Window over a `SymbolLayer`, because otherwise I could not customize it to my needs. If there is a way to do so via `SymbolLayer` / plugins I'll be glad to use them instead.

**Comment by langsmith** [comment]
@philoez98 , you can build a custom View and turn it into a Bitmap to use as a `SymbolLayer` icon. That's what's done in https://docs.mapbox.com/android/maps/examples/symbol-layer-info-window/

- https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/InfoWindowSymbolLayerActivity.java#L346-L365
- https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/InfoWindowSymbolLayerActivity.java#L379
- https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/InfoWindowSymbolLayerActivity.java#L242
