### ISSUE TITLE
 Reference the underlying Layer from AnnotationManager classes 

### ISSUE THREAD

**Issue by keinix** [mapbox/mapbox-plugins-android#1027]
I’m enjoying the ease of adding annotations to the map with the combination of the various AnnotationManager and Options classes, however I've run into a few problems that require the use of the Layer API. Seeing as the annotation plugin is a simpler, striped down version of this API, running into these types of issues is no surprise. I see a real benefit in the annotation plugin  coexisting with the classic Layer API in a project, but this is made more difficult without being able to reference an AnnotationManger’s underlying Layer.

Example Problems:

- SymbolOptions:  .withIconSize() only accepts a static size as a float.
SymbolLayer: .setProperties() allows size to be defined as an Expression that scales the symbol based on the zoom level
(A different solution to this particular case is being tracked in #736)

- Dynamically inserting and removing layers with AnnotationManger is tricky to handle. AnnotationMangers support a constructor with a belowLayerId parameter which is difficult to use with automatically generated layer ids.

Adding extra properties to or rearranging the underlying layers would be trivial, but when using multiple AnnotationMangers (as per PR  #941) it becomes cumbersome to keep track of which layers corresponds to which AnnotationManager.

Would it be possible to add a way to either:
a. Publicly reference the underlying Layer from an AnnotationManger
b. Set a custom Layer id from an AnnotationManger
c. Publicly reference the underlying layer’s automatically generated id from an AnnotationManger

**Comment by LukasPaczos** [comment]
Hey @keinix, thanks for reaching out.

> a. Publicly reference the underlying Layer from an AnnotationManger

I don't think we can expose the `Layer` object or recommend setting custom properties on those underlying `Layer`s because it's going to compete with the plugin's implementation and overwrite each other. We'll need to wait for https://github.com/mapbox/mapbox-plugins-android/issues/736 as a clean solution, otherwise, the raw API should be used, not the plugin wrapper.

> b. Set a custom Layer id from an AnnotationManger
c. Publicly reference the underlying layer’s automatically generated id from an AnnotationManger

I think we can expose those to make relative positioning easier to manage.

**Comment by p-fischer** [comment]
> c. Publicly reference the underlying layer’s automatically generated id from an AnnotationManger

That's exactly what I would need as well. 
I can share my use case:
In my implementation I require the symbol layer ID at some point. In version 0.6.0 I could access it via `SymbolManager.ID_GEOJSON_LAYER`.
Since https://github.com/mapbox/mapbox-plugins-android/pull/941 this is not possible anymore.
I thought about accessing the `SymbolManger`'s `layer` field via reflection but since I'm only using one symbol layer at a time I went with  `style?.layers?.find { it.id.contains("symbol") }`.
Both approaches can easily break with future implemenation changes without me noticing at compile time.

That being said I really enjoy the simplification this plugin provides. Keep up the good work!
