### ISSUE TITLE
Add fixed width option to scale bar

### ISSUE THREAD

**Issue by englezakis** [mapbox/mapbox-plugins-android#1046]
Tried the scale bar and it works and looks great. It would be nicer though if you could define a fixed horizontal size for the Scale Bar so that it doesn't constantly resize itself. The auto resize sometimes takes up half the screen.
Thanks

**Comment by Chaoba** [comment]
@englezakis Thanks for reporting this. I want to confirm the fixed horizontal size, is it mean the width of scale bar is fixed and never change?  If it is, that means we have to change the up distance number according to current zoom level and scale bar size, so the number may be something like 253km, which may not tidy.
If you think the size takes up half the screen troubles you, we can change the distance array defined in codes to make it shorter. Does it make sense to you?

**Comment by virtuoso80** [comment]
Yes, you understood my thoughts exactly. The problem is an aesthetic one, noticeable when working on tablets in landscape.
![scalebar](https://user-images.githubusercontent.com/51618112/64226250-52987080-cee7-11e9-872d-0a10f0a759dc.png)
 However, you are right, having an arbitrary number like 253km may not be tidy. So I think the best solution is what you suggest. Add an option to make the scale bar overall shorter, re-sizable still, and displaying only integer numbers.

**Comment by virtuoso80** [comment]
Thanks guys I'll try the new feature as soon as possible

**Comment by virtuoso80** [comment]
Tried the new functionality. Works great. Thanks a million for the support.
