### ISSUE TITLE
PlaceAutoComplete not working perfectly

### ISSUE THREAD

**Issue by chanaso** [mapbox/mapbox-plugins-android#1109]
Hi,
i have some issue with place AutoComplete.
it is working.
But it offers limited number of addresses(in my country -IL), and some existing addresses do not offer at all :/

any idea how to solve/improve it?
thank u :)

**Comment by langsmith** [comment]
Hi @chanaso , thanks for the ticket and for using Mapbox. 

`IL` = Israel? Hebrew is mentioned at https://docs.mapbox.com/api/search/#local-coverage. You can use the Mapbox Geocoding Playground to explore. All of the various settings and toggles in the Playground have their counterparts in the Places Plugin 

https://docs.mapbox.com/search-playground/#{%22url%22:%22%22,%22index%22:%22mapbox.places%22,%22approx%22:true,%22staging%22:false,%22onCountry%22:false,%22onType%22:true,%22onProximity%22:false,%22onBBOX%22:false,%22onLimit%22:false,%22onLanguage%22:true,%22countries%22:[],%22proximity%22:%2221.895759,43.320902%22,%22typeToggle%22:{%22country%22:false,%22region%22:false,%22district%22:false,%22postcode%22:false,%22locality%22:false,%22place%22:false,%22neighborhood%22:false,%22address%22:true,%22poi%22:false},%22types%22:[%22address%22],%22bbox%22:%22%22,%22limit%22:%22%22,%22autocomplete%22:true,%22languages%22:[{%22code%22:%22he%22,%22name%22:%22Hebrew%22}],%22languageStrict%22:false,%22onDebug%22:false,%22selectedLayer%22:%22%22,%22debugClick%22:{},%22localsearch%22:false,%22query%22:%22%22}

The information returned by the Places Plugin is based on the backend Mapbox Geocoding API. The ultimate answer to your question is probably that Mapbox's geocoding coverage in Israel isn't as thorough as you're looking for.

Because this ticket isn't an issue with the Places Plugin, but rather a Mapbox implementation question, please contact our support team via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231. The team is the best place to continue the conversation.
