### ISSUE TITLE
Latest versions not deployed to Maven Central

### ISSUE THREAD

**Issue by JRWilding** [mapbox/mapbox-plugins-android#1126]
At least

```
com.mapbox.mapboxsdk:mapbox-android-plugin-markerview-v7:0.4.0
com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v7:0.8.0
```

possibly more, have not been published to maven in a year

https://search.maven.org/artifact/com.mapbox.mapboxsdk/mapbox-android-plugin-markerview-v7
https://search.maven.org/artifact/com.mapbox.mapboxsdk/mapbox-android-plugin-annotation-v7

**Comment by langsmith** [comment]
Hey @JRWilding , thanks for reaching out. 

The plugins' prefixes match the Mapbox Maps SDK latest SEMVER major release number. We do this so that the plugin<–>map compatibility is a tad clearer.

The plugins now have the v9 prefix instead of v7 or v8 because `9.0.0` was the last SEMVER major release of the Maps SDK.

- https://search.maven.org/search?q=a:mapbox-android-plugin-markerview-v9
- https://search.maven.org/search?q=a:mapbox-android-plugin-annotation-v9

Here are instructions on installing these two plugins' latest versions:
- https://docs.mapbox.com/android/plugins/overview/annotation/#install-the-annotation-plugin
- https://docs.mapbox.com/android/plugins/overview/markerview/#install-the-markerview-plugin
