### ISSUE TITLE
New dependency configurations

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#140]
With Android Studio 3.0 and related Gradle version 3.4, developers have now more fine grained control over how a dependency can be consumed. See [this](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#new_configurations) table for more information. Ideally a plugin is developed against a SDK version but doesn't include the implemenation. The end developer/testapp will be responsible for providing the actual implementation.

**Comment by cammace** [comment]
I think I went for the `api` for the plugins which include the map SDK. Sounds like you were thinking instead of using the `implementation`? My reasoning was that the plugin will require the Map SDK anyways but if there's better reasoning behind why we should use `implementation` then I can change it.

**Comment by tobrun** [comment]
we need `implementation` on the plugins because we don't want to leak the SDK dependency. In the end it's the consuming app that will need to add a line in their gradle file indicating they want to use our SDK (in this repo case, it will be the testapp). This limits the issue of dependency/exclusion hell. Not matching versions of a plugin vs maps sdk will be detected at runtime.
