### ISSUE TITLE
Crash when changing location layer style right after MapView finishes loading style

### ISSUE THREAD

**Issue by Jukurrpa** [mapbox/mapbox-plugins-android#361]
Mapbox SDK version 5.5.0
Location layer version 0.4.0

At some point in my app, I change the style of the map and use a different drawable for the location layer. However if I change it right after getting the `MapView.DID_FINISH_LOADING_STYLE` event, the app segfaults (`Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 19072 (s.android.debug), pid 19072 (s.android.debug)`)

Code looks like this (simplified, in Kotlin):

    mapView.addOnMapChangedListener { change ->
        if (change == MapView.DID_FINISH_LOADING_STYLE) {
            locationLayerPlugin.applyStyle(
                    LocationLayerOptions.builder(context)
                            // etc
                            .build()
            )
        }
    }

Waiting for the first `MapView.WILL_START_RENDERING_FRAME` after the style is finished loading avoids the crash but causes some kind of flicker where the default drawable is used for a couple of frames, which isn't great.

Am I doing something wrong? Let me know if you need more info.

**Comment by cammace** [comment]
I believe this is happening because internally we are also using the same callback `DID_FINISH_LOADING_STYLE` to reload the location layer to the new map style. Can you try applying your new location layer style right before the map starts changing using the `WILL_START_LOADING_MAP` and seeing what happens?

**Comment by Jukurrpa** [comment]
I get the opposite result with `WILL_START_LOADING_MAP` where the desired drawable is used for a couple of frames and is then replaced by the default one.

**Comment by LukasPaczos** [comment]
Tested on `v0.5.3` that using `WILL_START_LOADING_MAP` is the right place to apply options that we want to use with the about to be loaded style. Another approach is using the `DID_FINISH_LOADING_STYLE` and posting the code block to the end of the UI thread queue, so that the internal initialization of layers and sources is guaranteed to happen beforehand.

Closing as resolved/not actionable. I hope this helps and let us know if you have any more questions.
