### ISSUE TITLE
PlaceAutocomplete crashes the ENTIRE app if network fails!!!

### ISSUE THREAD

**Issue by LouisCAD** [mapbox/mapbox-plugins-android#376]
The following line is the cause, but there may be others places where such code exists.
https://github.com/mapbox/mapbox-plugins-android/blob/0a4d416b7ba95ea7fabbdf04c3fd8f396fe077e2/plugin-places/src/main/java/com/mapbox/mapboxsdk/plugins/places/autocomplete/viewmodel/PlaceAutocompleteViewModel.java#L112
@cammace Why did you write this?

**Comment by langsmith** [comment]
@LouisCAD , if by `this`, you mean the entire PlacesAutoComplete plugin, he wrote this because we wanted to improve the Mapbox geocoding experience and to tie geocoding into other Mapbox tools such as the Mapbox Maps SDK for Android.

Issues will crop up time-to-time as our tools constantly evolve and improve. One of the benefits of being open-source is that you're able to alert us to this particular problem. We will look into it. Thank you.

**Comment by LouisCAD** [comment]
@langsmith I meant the linked line that throws a `RuntimeException` which crashes the entire app for what is just a network failure:
1. No one should throw `RuntimeException` for things like this, especially if they are not catchable, like here.
2. Don't you do code reviews to avoid things like this to get into production?
3. Don't you test your code against bad connectivity and no connectivity before releasing to production?

Anyway, I hope to see it fixed and to not encounter such a thing again.

**Comment by zugaldia** [comment]
@LouisCAD thanks for the additional information. You're right, this is a bug, the plugin shouldn't be crashing your app when a connection isn't available. We're actively working on a fix and we'll be posting more information as we have more to share.

Glad that you're using the plugin, please keep the feedback coming!

**Comment by cammace** [comment]
I've added a fix for this in https://github.com/mapbox/mapbox-plugins-android/pull/377, instead of throwing a runtime exception, we still log the error but display an offline message. Once merged, feel free to test out using the SNAPSHOT. Sorry for the inconvenience.
