### ISSUE TITLE
problem with bearing on location layer plugin

### ISSUE THREAD

**Issue by nole87** [mapbox/mapbox-plugins-android#429]
Dear,

I am using location layer plugin for my android app and while driving bearing is not correct look at attach. Other app has correct bearing and my don't. I have this:

 locationEngine = new LocationEngineProvider(this).obtainBestLocationEngineAvailable();

        locationEngine.setPriority(LocationEnginePriority.HIGH_ACCURACY);
        locationEngine.setFastestInterval(1000);

        locationEngine.activate();

and listener for it. I also try with android LocationManager to get location and force it to locationPluginLayer but it's same. I use 0.4 location plugin layer. It's really important to have correct bearing for my app.

![1 other app](https://user-images.githubusercontent.com/4254736/38862592-9fa4880e-4235-11e8-9f0e-4c35168f9d0c.png)
![1](https://user-images.githubusercontent.com/4254736/38862593-9fc86bc0-4235-11e8-9bb8-c1afd19d611c.png)
![2 other app](https://user-images.githubusercontent.com/4254736/38862594-9fe9052e-4235-11e8-818e-9611b8ecf857.png)
![2](https://user-images.githubusercontent.com/4254736/38862595-a00cc2d4-4235-11e8-80f7-6a25728b6fcb.png)
![3 other app](https://user-images.githubusercontent.com/4254736/38862596-a0339364-4235-11e8-95b5-d0f6149c75f3.png)
![3](https://user-images.githubusercontent.com/4254736/38862597-a05a0512-4235-11e8-9fee-5db8adda8f4d.png)

**Comment by cammace** [comment]
I'm only seeing a slight difference in compass bearing values. While there's no way to determine what sensors and how Google Maps determines the bearing, following the official Android documentation, I'm fairly confident that the compass values are coming from the correct sensors. Note that Google Maps is also giving you a bearing range were we are giving an exact value. 

The sensors also need collaboration occasionally which can typically be fixed by rotating your phone in a figure eight movement. I'd also recommend that if you are driving, navigation mode will most likely give you a more accurate bearing value since the values measured using the two most recent updates. 

Lastly, the compass value used for the location layer doesn't come from the location engine and is completely separate. If you find a flaw in our compass manager class or anywhere else, let me know and I'll happily investigate this issue but simply going off images makes this issue impossible to debug.

**Comment by nole87** [comment]
It's clear what you say but on picture you can see small difference and  a big 30-45 degree, I will try what you suggest me and investigate this a lot more but I know I must resolve this as soon as possible :)

**Comment by cammace** [comment]
Sounds good, Feel free to comment back on this issue when you find the issue.

**Comment by nole87** [comment]
I test it again, and I don't know sometimes it's correct and sometimes it isn't while in other app is correct, probably they use range for bearing and that's why it looks better in other app, for iOS same feature works great with mapbox! I will try to test it on other devices, I only have nexus 5.

**Comment by nole87** [comment]
I made conclusion today, google don't use compass sensors for displaying bearing they use gps bearing for that on android or they combine with compass sensors. With mapbox gps tracking gps marker has correct bearing. Problem is in compass sensors thet return incorrect result with gps bearing everything is OK! Is it possible to somehow change gps marker on android, in my opinion when I set to this like on picture it's to big, at least to make it smaller, on iOS I know there is option for this. Conclusion is that compass sensor are not good enough!

![screenshot_20180425-110848](https://user-images.githubusercontent.com/4254736/39244043-bc4e6938-488f-11e8-8522-94dbc9cac144.png)

**Comment by nole87** [comment]
with mapbox something like this:

LocationLayerOptions options = LocationLayerOptions.builder(MainActivity.this)
                            .accuracyAlpha(0)
                            //.gpsDrawable(R.drawable.gps)
                            .build();

                    locationLayerPlugin = new LocationLayerPlugin(mapView, mapboxMap, locationEngine, options);

                    locationLayerPlugin.onStart();

                        locationLayerPlugin.setRenderMode(RenderMode.GPS);

here is a link https://www.mapbox.com/android-docs/plugins/overview/location-layer/#usage-with-navigation
