### ISSUE TITLE
Location layer. Animations priority

### ISSUE THREAD

**Issue by psinetron** [mapbox/mapbox-plugins-android#461]
Location-layer 0.5.0
The camera mode cancels any other animation.
For example, I have the camera mode in the compass. In this mode, the camera rotates continuously. I'm trying to zoom in, but turning the compass cancels this action

Example:
```
// camera mode:
locationLayerPlugin?.cameraMode = CameraMode.TRACKING_COMPASS
locationLayerPlugin?.renderMode = RenderMode.COMPASS
```

```
//zoom in function cancelled:
fun zoomIn() {
        map?.animateCamera(CameraUpdateFactory.zoomIn())
}
```

Offtop:
How to set labels for issue?

**Comment by cammace** [comment]
Camera animations work a bit different in the Location Layer Plugin then you'd expect. We are using `ValueAnimator`s to interpolate the camera from one position to another or adjust the bearing (underneath, moveCamera is frequently being called). My assumption is that when you call `animateCamera`, the moveCamera is being called right after canceling your camera animation. You might have better luck, first, canceling the tracking mode and then calling the animate camera. 

@LukasPaczos do you have any other solutions for this?

**Comment by LukasPaczos** [comment]
As @cammace pointed out, we are using `ValueAnimator`s to track the camera, which means that in order to scale, or do any other programmatic camera change, you'll have two options:
- break tracking -> change camera position -> start tracking (for example with `MapboxMap#CancelableCallback` which fires when animation finishes)
- use `ValueAnimator`s and `MapboxMap#moveCamera`

The latter is definitely a better solution, but requires a bit more work.

**Comment by cammace** [comment]
Seems like nothing is actionable on our end here. Closing.
