### ISSUE TITLE
LocationLayer plugin 'can't find source for layer' problem

### ISSUE THREAD

**Issue by lorenzhahaha** [mapbox/mapbox-plugins-android#485]
<a href="https://ibb.co/cwCzTn"><img src="https://preview.ibb.co/k2KeTn/Screen_Shot_2018_05_05_at_4_45_37_PM.png" alt="Screen_Shot_2018_05_05_at_4_45_37_PM" border="0"></a><br>

<a href="https://ibb.co/fM0xES"><img src="https://preview.ibb.co/eoPPuS/Screen_Shot_2018_05_05_at_4_50_10_PM.png" alt="Screen_Shot_2018_05_05_at_4_50_10_PM" border="0"></a><br>

I don't know what really is the problem. What I did is just follow the instructions in <a href="https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/LocationPluginActivity.java">here</a> but I still can't see my location. I have read the documentation on how to implement this from <a href="https://www.mapbox.com/android-docs/plugins/overview/location-layer/">this link</a>. I thought that it was caused by the mixing of libraries but when I started a new project (which I have made for about 10+ times), I still face same warning. I am facing this problem for almost 3 days. I am so sad why do I can't get my location which is very simple in google map. What I just want is to implement mapbox which in the first phase is to get user's location. Please help me. 

**AS version: 3.1.2
Current emulator android version: API 27
Support version: 27.1.1**

Same problem even with Emulator or Physical device. I can't get user's location and also the blue gps icon.

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig { 
        applicationId "com.a1ks.toandfro" 
        minSdkVersion 19 
        targetSdkVersion 27 
        versionCode 1 
        versionName "1.0" 
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner" 
    }
    buildTypes { 
        release { 
            minifyEnabled true 
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro' 
        } 
    } 
    buildToolsVersion '27.0.3' 
    compileOptions { 
        sourceCompatibility JavaVersion.VERSION_1_8 
        targetCompatibility JavaVersion.VERSION_1_8 
    } 
}

dependencies {
implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "com.android.support:appcompat-v7:$support_version"
    implementation "com.android.support:design:$support_version"
    implementation "com.android.support:support-v4:$support_version"
    implementation "com.android.support:recyclerview-v7:$support_version"
    implementation "com.android.support:cardview-v7:$support_version"
    implementation "com.android.support:support-vector-drawable:$support_version"

    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.0.1'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-offline:0.1.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.5.0'
}

**Comment by cammace** [comment]
Thanks for the thorough information, this same issue has been reported to us a few times already (such as in https://github.com/mapbox/mapbox-plugins-android/issues/462) which has since been fixed on Master. We are now closing out the last few issues on the [0.5.1 milestone](https://github.com/mapbox/mapbox-plugins-android/milestone/9) and then a new release will happen with the fix. This release is scheduled to happen this week. In the meantime, if you need location on your map, you can use a SNAPSHOT version of the SDK (Id recommend targeting one that was built from master last mid-week). Our README shows an example on how to use the latest snapshot version. To specifically target a SNAPSHOT build, head over to [sonatype](https://oss.sonatype.org/content/repositories/snapshots/com/mapbox/mapboxsdk/mapbox-android-plugin-locationlayer/0.6.0-SNAPSHOT/) find the date of the one you'd like to use, and add the dependency in your apps build.gradle file using the full hash naming scheme. For example, for May 2nd, `0.6.0-20180502` would be the SNAPSHOT version.

**Comment by lorenzhahaha** [comment]
@cammace Thanks for your feedback but still facing same issue even using the snapshot version that you have provided. I also tried different snapshot versions close to what you gave to me. The problem keeps coming with that 'cannot find source for layer'. Another thing, when I used the snapshot version, map becomes buggy that different landmarks and even the gps puck is black. Lastly, I thought it was on the device that it was happening so I have used 2 physical devices, api 19 and api 25, and with 2 virtual device of api 19 and api 27, all of them have same result, 'cannot find source for layer'. But the difference only is that in the virtual device, it really get the location but with black marks on map and the puck but on physical device, it failed.

**Comment by cammace** [comment]
The black puck or icon issue is due to you using a symbol layer on a virtual device, an issue on our end but not necessarily a high priority for us to fix on the Map SDK side since it only occurs on emulators. If you are switching between SNAPSHOT versions and testing, can you try clearing or refreshing your gradle cache to make sure it's not still targeting a version it's not supposed to.
