### ISSUE TITLE
Support usage of images already loaded in map style for location layer drawables

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-plugins-android#486]
Pointed out in https://github.com/mapbox/mapbox-plugins-android/issues/183#issuecomment-356668734, it makes sense to also allow users to use the bitmap id which defines the sprite inside the map style for their location layer icons.

**Comment by DejanRistic** [comment]
@cammace is there a ETA for getting this into the snaphsot build? We are looking to migrate over to mapbox 6.x so we aren't to behind, but can't make the switch until the location plugin has support for this as we would lose a feature without it. And 6.x sort of requires us to move to the location plugin, I guess i could fork the plugin and expose the methods for the short term. 

Just curious, Thanks!

**Comment by DejanRistic** [comment]
@LukasPaczos I've been testing this feature out and have been running into some issues. After adding images to our mapbox map instance and initializing the location plugin the custom images don't seem to show up right away and sometimes disappear. 

Example of how i'm setting it up:

After our map is ready, I add a custom image to the map.
```
    private void addDefaultAvatarBackground() {
        Drawable background = ContextCompat.getDrawable(getActivity(), R.drawable.shape_circle_white);
        Bitmap bitmapBackground = BitmapUtils.getBitmapFromDrawable(background);
        if (bitmapBackground != null) {
            map.addImage("backgroundAvatar", bitmapBackground);
        }
    }

// same with foreground.
``` 

Later when the user permissions are granted and all that fun stuff we init the plugin:
```
locationLayerPlugin = new LocationLayerPlugin(mapView, map, locationEngine);
locationLayerPlugin.applyStyle(defaultLocationLayerOptions());
locationLayerPlugin.setLocationLayerEnabled(true);
```

```
    private LocationLayerOptions defaultLocationLayerOptions() {
        return LocationLayerOptions.builder(getActivity())
                .elevation(4.f)
                .accuracyAlpha(0.f)
                .foregroundName("foregroundAvatar")
                .backgroundName("backgroundAvatar")
                .build();
    }
```

Now when the map is shown instead of the custom image showing up right away i'm just seeing the default dot image shown. After leaving the view our map is on and returning to it a few times (inconsistent) the custom image shows up eventually. After it shows up, i've noticed it disappear randomly when switching to different styles. 

Is there a certain way I should be refreshing the map after applying the location plugin to force these updates?
