### ISSUE TITLE
onRotation, puck gets disabled

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-plugins-android#517]

**Comment by LukasPaczos** [comment]
Not seeing this issue on `v0.5.3`. Since we are not inlcuding any saving state logic, the visibility of the puck after rotation seems to be affected only by the `LocationEngine` setup and the time it takes to obtain the first location sample.

Noting, that if somebody would like to ensure that a puck is visible straight after rotation, not depending on the `LocationEngine`'s availability, last `Location` should be saved using save state mechanisms and pushed to the `LocationLayerPlugin#forceLocation` straight after state is restored.
