### ISSUE TITLE
How to update with new data in Cluster Plugin

### ISSUE THREAD

**Issue by samirshrestha** [mapbox/mapbox-plugins-android#518]
Is there any option to update the map with new data(eg. data filtered with some criteria) in the Cluster Plugin?

**Comment by cammace** [comment]
TBH we should just deprecate and delete the cluster plugin. It only offers users the ability to use GLMarkers which we should stop encouraging as much as possible due to their limited API set. Instead, pushing the GeoJSON clustering capability (shown in [this example](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/GeoJsonClusteringActivity.java)). In my opinion @samirshrestha, this is the path forward you should take if you wish to update cluster icons during runtime. You can make a GeoJSON FeatureCollection containing all your points, add it as a source, and update the source whenever you please. Runtime styling can be used to style the markers.

cc: @tobrun @zugaldia
