### ISSUE TITLE
LocationLayerPlugin: Custom LocationEngine can't be implemented

### ISSUE THREAD

**Issue by stoefln** [mapbox/mapbox-plugins-android#552]
I am currently trying to implement my own LocationEngine but it's not possible.
The locationLayerPlugin (v0.5.3) is expecting a **com.mapbox.services.android.telemetry.location.LocationEngine** object, but for some reason this class can't be extended.
Looking at your master branch code, you seem to have changed that recently:
The plugin is now expecting a **com.mapbox.android.core.location.LocationEngine**

I am confused. Can someone help me with this?

**Comment by danesfeder** [comment]
Hey @stoefln, we've recently updated our `LocationEngine` code to live in `com.mapbox.android.core.location.LocationEngine` - do you mind sharing your Mapbox dependencies?  This may just be a matter of removing older ones that are conflicting with these updates.  

To be clear, `com.mapbox.android.core.location.LocationEngine` is the `LocationEngine` you should be extending to pass through the constructor of `LocationLayerPlugin`.  Thanks!

**Comment by stoefln** [comment]
@danesfeder What dependencies do you mean? I just use LocationLayerPlugin (which also installes MapBox as dependency). That's it.

**Comment by LukasPaczos** [comment]
@stoefln looking at the `v0.5.3` tag, it was shipped with [com.mapbox.android.core.location.*](https://github.com/mapbox/mapbox-plugins-android/blob/3810f6da6392a7a6ac3fb2daf9098755456dd4c6/plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPlugin.java#L14-L17) package as the home for the `LocationEngine`. I also had no troubles when testing it out in a brand new project locally.

As @danesfeder mentioned, would you mind sharing your dependencies setup and invalidate your caches/sync project with gradle again?

**Comment by stoefln** [comment]
@LukasPaczos Thanks for the tip. I invalidated the caches and now things work as they should...

**Comment by stoefln** [comment]
However, I am having more issues with implementing my own LocationEngine now. It seems the only method called is **getLastLocation()**.
Is there an example somewhere out there?

**Comment by LukasPaczos** [comment]
When you are passing your own `LocationEngine` instead of using a built-in one you need to manage its state yourself - this means activating/deactivating and requesting location updates. Please refer to the [`LocationEngine` docs](https://www.mapbox.com/android-docs/core/overview/#locationengine) if you have any questions.

If you'd rather use the built-in one, use a [constructor](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPlugin.java#L96-L102) that doesn't take engine as a parameter.

Closing as answered. Don't hesitate to reach out if you have any more issues.
