### ISSUE TITLE
java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@7853e03 does not exist

### ISSUE THREAD

**Issue by sfariv** [mapbox/mapbox-plugins-android#781]
Hi, my app is crashing when I use `com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.6.0` it works just fine with version `0.5.3`. basically any version after `0.5.3` has this issue:

`java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@7853e03 does not exist
        at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8774)
        at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8765)
        at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1222)
        at android.os.BinderProxy.sendDeathNotice(Binder.java:558)`

Please provide me an email address so I can send you a sample project that shows the crash.

**Comment by LukasPaczos** [comment]
Thanks for reaching out @sfariv. `plugin-locationlayer:0.6.0` is an extremely outdated version, we won't be able to realistically provide any support here. Please use the `LocationComponent` that's a part of the most recent Mapbox Maps SDK releases and let us know whether the issue is reproducible there as well. You can follow [the documentation](https://www.mapbox.com/android-docs/maps/overview/location-component/) during setup.

**Comment by sfariv** [comment]
@LukasPaczos the crash is happening with any version greater than `0.5.3`, please read my comment more carefully. which includes your latest one.

**Comment by LukasPaczos** [comment]
If this is reproducible using the `LocatioComponent`, feel free to open a new issue [here](https://github.com/mapbox/mapbox-gl-native/issues). Thanks!
