### ISSUE TITLE
Crash Due to Null Pointer Exception when using mapbox-android-plugin-places

### ISSUE THREAD

**Issue by gauravk95** [mapbox/mapbox-plugins-android#816]
This crash is caused when using **mapbox-android-plugin-places**
Mapbox SDK Version: 0.6.0

**Device:**
Brand: LENOVO
Model: Lenovo A6010
Orientation: Portrait
RAM free: 570.79 MB
Android Version: 5.0.2

**Stacktrace:**
```
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
android.support.v4.content.PermissionChecker.checkPermission (Unknown Source)
com.mapbox.android.telemetry.TelemetryService.locationPermissionCheck (Unknown Source)
com.mapbox.android.telemetry.TelemetryService.connectLocationEngine (Unknown Source)
com.mapbox.android.telemetry.TelemetryService.registerLocationReceiver (Unknown Source)
com.mapbox.android.telemetry.TelemetryService.createLocationReceiver (Unknown Source)
com.mapbox.android.telemetry.TelemetryService.onCreate (Unknown Source)
android.app.ActivityThread.handleCreateService (ActivityThread.java:2743)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:693)
```

**Comment by LukasPaczos** [comment]
Hey @gauravk95, thanks for reaching out!. This crash has been resolved upstream and the fix is available in the `mapbox-android-plugin-places-v7:0.7.0`.

`v0.7.0` brings a major Maps SDK bump, so if you'd like to use `mapbox-android-plugin-places:0.6.0` you can manually include Maps SDK dependency on version `6.8.1` to resolve the issue.
