### ISSUE TITLE
Circle should not change size on zoom !

### ISSUE THREAD

**Issue by ben-j69** [mapbox/mapbox-plugins-android#847]
I use the new CircleManager to draw an accuracy circle around my point (for exemple a radius a 100m) but when the user zoom or unzoom on the map the circle stay on the same size and does not represent 100m anymore because the scale of the map has changed but the circle remain the same.

**Comment by LukasPaczos** [comment]
Hey @ben-j69, thanks for using Mapbox! Unfortunately, this is blocked upstream https://github.com/mapbox/mapbox-gl-native/issues/4312. Fwiw, you can try and correctly scale the circle yourself, see [this solution](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/Utils.java#L88-L94).

**Comment by androideveloper** [comment]
How to scale it with minimum boilerplate?

**Comment by Danm72** [comment]
Any update on this?

**Comment by elroid** [comment]
This is very much still an issue, and I'm unclear why it appears to be so fundamentally blocked. I'd venture to guess the vast majority of your users will be coming from a similar deployment using Google Maps, and there's no reason to expect that this crucial aspect works differently to the way it does there - especially since just about everything else in the MapBox SDK mirrors it so closely. I'm not even clear what the point of being able to draw a fixed-size circle over a map is. If the state of the map view was irrelevant I could draw something similar to this using a normal Android view and just place it on top of the MapView.
At the very least, if this problem is not going to be addressed (and after 4 years of discussion, I'm not holding my breath), there should be a clear example somewhere of how to draw a geographically-static-sized circle using the existing SDK. I've spent the last hour trying to establish the approved workaround and I'm so far none the wiser. :-(

**Comment by ben-j69** [comment]
@elroid maybe this can help you

` @Deprecated
    @Nullable
    public static Polygon drawZoneCircle(@Nullable MapboxMap map, @NonNull LatLng centerCoordinates,
                                         double radiusInKilometers) {
        if (map == null) {
            return null;
        }
        PolygonOptions opts = MapUtils.generatePerimeter(centerCoordinates,
                radiusInKilometers / 1000f, MapUtils.CIRCLE_SIDES);

        final int fillColor = ContextCompat.getColor(KlaxitApp.getContext(), R.color.green_dark_status);
        opts.fillColor(Color.argb(255,
                Color.red(fillColor),
                Color.green(fillColor),
                Color.blue(fillColor)));
        return map.addPolygon(opts);
    }

    @Deprecated
    @Nullable
    public static PolygonOptions generatePerimeter(@NonNull LatLng centerCoordinates,
                                                   double radiusInKilometers,
                                                   int numberOfSides) {
        List<LatLng> positions = new ArrayList<>();
        double distanceX = radiusInKilometers / (111.319 * Math.cos(centerCoordinates.getLatitude() * Math.PI / 180));
        double distanceY = radiusInKilometers / 110.574;

        double slice = (2 * Math.PI) / numberOfSides;

        double theta;
        double x;
        double y;
        LatLng position;
        for (int i = 0; i < numberOfSides; ++i) {
            theta = i * slice;
            x = distanceX * Math.cos(theta);
            y = distanceY * Math.sin(theta);

            position = new LatLng(centerCoordinates.getLatitude() + y,
                    centerCoordinates.getLongitude() + x);
            positions.add(position);
        }
        return new PolygonOptions()
                .addAll(positions)
                .alpha(0.25f);
    }`
