### ISSUE TITLE
CircleManager.create(json) Documentation Question

### ISSUE THREAD

**Issue by Yermo** [mapbox/mapbox-plugins-android#849]
Two questions where the documentation seems lacking (or maybe I'm missing something basic): 

1) I am working with the [nativescript-mapbox](https://github.com/EddyVerbruggen/nativescript-mapbox) plugin to bring it in line with Mapbox Android Native 7.1.2. 

I am attempting to use the annotations plugin to draw a circle that resizes as the map is zoomed (using stops) and capture click events. 

I noticed the [create(json](https://docs.mapbox.com/android/api/plugins/annotation/0.5.0/com/mapbox/mapboxsdk/plugins/annotation/CircleManager.html#create-java.lang.String-)) method. 

It says:

> Circles are going to be created only for features with a matching geometry.
>
> You can inspect a full list of supported feature properties in CircleOptions.fromFeature(Feature).

Is the JSON parameter it accepts a Mapbox style or just a geojson document? (the comment about feature properties is what is making me wonder.) 

Is there an example somewhere?

When I call create() with either a mapbox style that works in mapbox-gl-js or with a simple geojson geometry I get no error but it returns an empty array and nothing is drawn on the map. I suspect I am missing something basic. 

The style I've been using that works in mapbox-gl-js.
`
{
      "id": 'testCircle',
      "type": 'circle',
      "circle-radius": 250,
      "source": {
        "type": 'geojson',
        "data": {
          "type": "Feature",
          "geometry": {
            "type": "Point",
            "coordinates": [ -76.947041, 39.007846 ]
          }
        }
      }, 
      "paint": {
        "circle-radius": {
          "stops": [
            [0, 0],
            [20, 6000 ]
          ],
          "base": 2
        },
        'circle-opacity': 0.05,
        'circle-color': '#ed6498',
        'circle-stroke-width': 2,
        'circle-stroke-color': '#ed6498'
      } `

I wasn't able to find an example of how this is supposed to work in the demos. 

2)  Is it possible to create a layer using the [Circle layer](https://docs.mapbox.com/android/api/map-sdk/7.1.2/com/mapbox/mapboxsdk/style/layers/CircleLayer.html) and somehow capture click events on it using the Annotations plugin? The reason I ask is that the mention of [ID_GEOJSON_LAYER](https://docs.mapbox.com/android/api/plugins/annotation/0.5.0/com/mapbox/mapboxsdk/plugins/annotation/CircleManager.html) seems to imply that maybe that's possible?

**Comment by LukasPaczos** [comment]
Hey @Yermo, thanks for reaching out!

The `String` that is accepted by the `CircleManager#create` method should be a simple [geojson](http://geojson.org/), for example [this test file](https://raw.githubusercontent.com/mapbox/mapbox-plugins-android/master/app/src/main/assets/annotations.json), with properties that define the options otherwise found in the `CircleOptions` builder (see [the full list](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-annotation/src/main/java/com/mapbox/mapboxsdk/plugins/annotation/CircleOptions.java#L237-L254)). Unfortunately, as `Expression`s are not considered per symbol, but rather per layer, those cannot be set from a JSON and can only be applied at the `CircleManager` level.

Under the hood, every manager has its own layer (that you pointed to) and exposes click listeners that are invoked after processing the return value of the `MapboxMap#queryRenderedFeatures`. You cannot route any external `Layer` click through the annotation manager, you'd have to implement this logic yourself.

Also, I'm now noticing that our API reference docs are not listing the possible properties because they come from a package-private method. We should probably move the list to the public method's javadoc. Keeping the ticket open until that's resolved.

**Comment by Yermo** [comment]
Thank you for the prompt reply!

I have gotten the JSON you provided working. Excellent.

Is there support for 'stops' on the circle radius? I see a [withCircleRadius()](https://docs.mapbox.com/android/api/plugins/annotation/0.5.0/com/mapbox/mapboxsdk/plugins/annotation/CircleOptions.html#withCircleRadius-java.lang.Float-) method that accepts a float.

With the Circle layer support I was able to use stops to resize the circle proportional to the zoom level. I don't see how that is done with the Annotations.

**Comment by LukasPaczos** [comment]
Unfortunately, annotation plugin doesn't support `Expression`s yet, https://github.com/mapbox/mapbox-plugins-android/issues/736 is tracking that.

**Comment by Yermo** [comment]
Ok. Thank you again for the prompt reply.

**Comment by Yermo** [comment]
One last quick question, what is the format of the argument to withLinePattern()? I see it's a string but there's no mention. I am guessing this is something similar to the dash-array feature of a LineLayer?

Thank you again for all your help.

**Comment by Yermo** [comment]
Just a note for the documentation. It should probably mention that create( JSON ) requires the geoJSON to be a FeatureCollection. Passing it a single Feature does not seem to work (although it does not generate an error message, just an empty return value).

**Comment by LukasPaczos** [comment]
Yes, this is something we should improve as a takeaway from this ticket.

When it comes to the `withLinePattern`, you can read more about the argument in [the style specification](https://docs.mapbox.com/mapbox-gl-js/style-spec/#paint-line-line-pattern).

**Comment by Yermo** [comment]
ah. Thank you.
