### ISSUE TITLE
LineManager.setLineDashArray() documentation question

### ISSUE THREAD

**Issue by Yermo** [mapbox/mapbox-plugins-android#851]
I would like to be able to draw dashed lines on a map that receive click events. 

I have just noticed the [LineManager.setLineDashArray()](https://github.com/mapbox/mapbox-plugins-android/blob/f07cea67606b0e979087eefa07814b2834c55d45/plugin-annotation/src/main/java/com/mapbox/mapboxsdk/plugins/annotation/LineManager.java#L299) method.

How is this method supposed to be used?

Does this set the dash array property for all lines managed by the instance of the LineManager?

Are there any plans to add these other style properties to the list of [LineOptions](https://docs.mapbox.com/android/api/plugins/annotation/0.5.0/com/mapbox/mapboxsdk/plugins/annotation/LineOptions.html)?

**Comment by LukasPaczos** [comment]
Hey @Yermo, thanks for reaching out!
> How is this method supposed to be used?

Please refer to [the style specification](https://docs.mapbox.com/mapbox-gl-js/style-spec/#paint-line-line-dasharray).

> Does this set the dash array property for all lines managed by the instance of the LineManager?

Yes.

> Are there any plans to add these other style properties to the list of [LineOptions](https://docs.mapbox.com/android/api/plugins/annotation/0.5.0/com/mapbox/mapboxsdk/plugins/annotation/LineOptions.html)?

In this sepcific case, no, because the `line-dasharray` is not data-driven and we cannot change the pattern for each separate line in the `LineManager` based on the provided data. For each new pattern you'll have to create a new instance of the `LineManager` as mentioned above.

**Comment by Yermo** [comment]
Thank you.
