### ISSUE TITLE
Iran/Farsi localization is not work anymore

### ISSUE THREAD

**Issue by radeshf** [mapbox/mapbox-plugins-android#852]
I used localization plugin version 0.5.0 and use MapLocale.ARABIC local for changing labels to persian (please add PERSIAN) and every thing work fine and all the labels turns to persian.

After update mapbox to version 7.1.2 and plugin-localization-v7 to 0.8.0 no more Persian lables on map.

I use this code

    
         @Override
          public void onMapReady(@NonNull MapboxMap mapboxMap) {
                mapboxMap.setStyle(Style.MAPBOX_STREETS, style -> {
                       if (mapStyle.isFullyLoaded){
                            LocalizationPlugin localizationPlugin = LocalizationPlugin(mapView, map , style )
                            localizationPlugin.setMapLanguage(MapLocale(MapLocale.ARABIC))
                        }else{
                            Timber.e("Mapbox LocalizationPlugin won't loaded, The style has to be non-null and fully loaded.")
                }
          }

Result in mapbox 6.8.1 and  plugin-localization to 0.5.0

![photo_2019-02-24_11-48-47](https://user-images.githubusercontent.com/20123581/53296954-1cd54980-382b-11e9-9f2c-a0b90803ee7d.jpg)

Result in mapbox 7.1.2 and plugin-localization-v7 to 0.8.0

![photo_2019-02-24_12-01-40](https://user-images.githubusercontent.com/20123581/53297004-0da2cb80-382c-11e9-94c2-e351596c624a.jpg)

Here is Isfahan city in Iran with lat:32.646693 , lng:51.668172

**Comment by LukasPaczos** [comment]
Hey @radeshf, thanks for using Mapbox! Recently, when adding support for the `street-v8` sources, we've changed the fallback logic of the plugin - whenever we don't have matching labels (in this case Arabic), we'll fall back to local labels but only if the local language is using Latin script, otherwise, we'll fall back to English labels.

Maybe this logic doesn't provide the best UX when both localized and local labes are using a language written right to left? @nickidlugash @zugaldia @julianrex what do you think about exposing an `alwaysFallbackToLocal` flag that when set would always try to use local labels for fallbacks? I think this would give enough flexibility to cover most of cases like the OP.

**Comment by zugaldia** [comment]
> what do you think about exposing an `alwaysFallbackToLocal` flag that when set would always try to use local labels for fallbacks?

:+1: makes sense to me.

**Comment by nickidlugash** [comment]
> I used localization plugin version 0.5.0 and use MapLocale.ARABIC local for changing labels to persian (please add PERSIAN) and every thing work fine and all the labels turns to persian.

> After update mapbox to version 7.1.2 and plugin-localization-v7 to 0.8.0 no more Persian lables on map.

I am not that familiar with the implementation details of how to use this plugin, so I may just be misunderstanding something, but is there a reason why for this use case the `MapLocale` is set to `ARABIC` rather than to `LOCAL_NAME`, if the goal is to have Persian labels in areas where Persian is the local language?

> we'll fall back to local labels but only if the local language is using Latin script, otherwise, we'll fall back to English labels.

@LukasPaczos To clarify, by "otherwise, we'll fall back to English labels" do you mean that we'll otherwise fall back to English labels FIRST, but then still fall back to local labels if an English label does not exist?

Regarding any potential updates to the plugin behavior, I think it might be simpler for users if instead of creating a new flag, we change the default logic for all specified languages to fall back to the local language if the local language is in the same script as the specified language, otherwise fall back to English first, then local language second. This essentially would slightly change the behavior for all non-Latin language options (Arabic, Russian, Simplified Chinese, Traditional Chinese, Japanese, Korean), while keeping the Latin language options unchanged. I think this behavior would most widely meet our users needs. Happy to discuss this further in a new ticket if it seems reasonable.

**Comment by LukasPaczos** [comment]
> ... but is there a reason why for this use case the MapLocale is set to ARABIC rather than to LOCAL_NAME, if the goal is to have Persian labels in areas where Persian is the local language?

I was under the impression, that the goal is to have Arabic labels when possible and fall back to Persian instead of English. Please correct me if I'm wrong @radeshf.

> Regarding any potential updates to the plugin behavior, I think it might be simpler for users if instead of creating a new flag, we change the default logic for all specified languages to fall back to the local language if the local language is in the same script as the specified language, otherwise fall back to English first, then local language second.

I really like this idea as a default behavior! However, I still think that exposing an option to fall back straight to `LOCAL_NAME` instead of English first might be desirable in some scenarios. Do you think that this could be hidden under a flag?

**Comment by radeshf** [comment]
I read this in doc

`@param mapLanguage a non-null string which is allowed from {@link Languages}`

So i see the languages in MapLocale.java and closest option to farsi is arabic so i choose it and labels turns to farsi and i use that for several month until i updated library versions. 

I think you set both farsi and arabic labels as one language and after update it separate to two different source so when i set to Arabic it fall back to English

thanks to @nickidlugash, now i try this and all labels turn to farsi and i wonder too why don't use this till now!

`localizationPlugin.setMapLanguage(MapLocale(MapLocale.LOCAL_NAME))`

**Comment by LukasPaczos** [comment]
Happy to hear that you've resolved your issue @radeshf! Let's move the default fallbacks conversation to a separate ticket.
