### ISSUE TITLE
Order of initialization of annotation managers matters!

### ISSUE THREAD

**Issue by androideveloper** [mapbox/mapbox-plugins-android#863]
I have found a weird bug! When you initialize symbol manager and the circle manager, your symbol can't be dragged! If you change the order of initialization it works!

### Steps to reproduce

Demo https://www.dropbox.com/s/ympu7zg722vehty/MapboxSymbolDragDemo.zip?dl=0

Try to change order of initialization:
 symbolManager = SymbolManager(mapView, mapboxMap, style)
 circleManager = CircleManager(mapView, mapboxMap, style)

### Expected behavior

Symbol should be draggable in any case

### Actual behavior

Symbol is draggable only, if circle manager initialized first

### Configuration

**Android versions:** 9.0
**Device models:** Xiaomi mi 2 lite
**Mapbox SDK versions:** 7.2.0, plugin-annotation-v7:0.5.0

**Comment by LukasPaczos** [comment]
This is an interesting case, thanks for the report @androideveloper.

Because we are using `mapView.setOnTouchListener()` to intercept touch events, **only the last created manager will have draggable annotations**.

There seem to be 2 ways of resolving this:
- make `DraggableAnnotationController` a singleton that dispatches drag events to all managers
- expose a way to intercept map touch events before they are passed to the internal gestures manager. This would also resolve https://github.com/mapbox/mapbox-plugins-android/issues/884 as we wouldn't have to rely on the `OnTouchListener`.

Will update this ticket with progress, if we find any of above viable.

**Comment by androideveloper** [comment]
@LukasPaczos Thanks for the update! I will keep it as the last created manager until this is resolved.

**Comment by adrianababakanian** [comment]
We should re-open this, since recent [reports on Stack Overflow](https://stackoverflow.com/questions/60266329/android-problem-with-2-annotation-type-in-mapbox/60859256#60859256) indicate that developers are still encountering the issue.

**Comment by m0nac0** [comment]
We're also encountering this in the mapbox_gl flutter plugin (tracked at https://github.com/tobrun/flutter-mapbox-gl/issues/130). This is kind of significant, as it means that we can only have one draggable annotation type.

**Comment by m0nac0** [comment]
@adrianababakanian @LukasPaczos Sorry for spamming, but do you know if this is being worked on? Otherwise we'd have to find some workaround for the mapbox_gl flutter plugin to support draggable annotations.

**Comment by virtuoso80** [comment]
Hello. Has there been a workaround for this? My application stops registering drag events after setting `mapview.setOnTouchListener(null)` 
when following this guide [](url)  https://docs.mapbox.com/android/maps/examples/finger-draw-query/
