### ISSUE TITLE
CircleManager annotations.size() not change after delete circle.

### ISSUE THREAD

**Issue by boybeak** [mapbox/mapbox-plugins-android#872]
I have tried `circleManager.delete`, `circleManager.annotations.removeAt(i)`, `circleManager.annotations.remove(key)` and even `circleManager.annotations.clear()`. But the size of annotations never change. It seems to be a bug? Or your team design so.
What i really need is changing the Circle's style for different states. At this moment, I have to delete the old circle and create a new style one. Is there a better way to solve the problem?

**Comment by tobrun** [comment]
@boybeak thank you for reaching our and using our products.
Sadly, I'm not able to reproduce this with a manual test or with an [automated one](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-annotation/src/test/java/com/mapbox/mapboxsdk/plugins/annotation/CircleManagerTest.java#L183).
Could you add a minimal reproducible test case?

**Comment by boybeak** [comment]
@tobrun I create a circle with *[latitude=39.92223841, longitude=116.35534728, altitude=57.615966796875]* and click the circle, but in OnCircleClickListener's callback method, it gives me a circle without altitude *[latitude=39.92223841, longitude=116.35534728, altitude=0.0]*.  
The altitude variable get lost. So in some conditions, when I try to find the circle with latlng and then delete it, this may failed.

**Comment by tobrun** [comment]
@boybeak under the hood we do not actually use LatLng but Point geometry data. This geometry and the layers responsible for rendering them don't have the concept of altitude. The LatLng API is only there for ease-of-use. The correct way to handle this is either to store the Annotation itself, store the id or use geometry instead of LatLng. 

I'm leaning towards not supporting this specific case. You should rely on the object and the equals implementation to verify if one circles is another circle.
