### ISSUE TITLE
LocationLayer below polyline (from directions route)

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-plugins-android#95]
**'mapbox-android-plugin-locationlayer', version: '0.2.0-SNAPSHOT'** and **version: '0.1.0'**

The location layer plugin is below the route. Am I doing something wrong?

![2017-08-30 16 20 04](https://user-images.githubusercontent.com/23097192/29877321-90b30ac8-8d9f-11e7-858e-b5fc7ab70a3a.jpg)

**Comment by cammace** [comment]
It looks like you are drawing a polyline on the map rather than using runtime styling to draw it. You might want to have a look at the [NavigationMapRoute](https://github.com/mapbox/mapbox-navigation-android/blob/master/navigation/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationMapRoute.java) class which will draw the route line for you. The reason for the route being drawn on top currently is because the polyline layer gets drawn after the location layer icon in the map layer stack. Currently, there are no plans to change this behavior.

**Comment by P-Zenker** [comment]
You're right. I've used an old version to show the directions route, thanks for the hint. 
Now my code is:

```
    private static final String NAVIGATION_ROUTE_SOURCE = "mapbox-plugin-navigation-route-source";
    private static final String NAVIGATION_ROUTE_LAYER = "mapbox-plugin-navigation-route-layer";

        LineString lineString = LineString.fromPolyline(directionsRoute.getGeometry(), Constants.PRECISION_6);
        FeatureCollection featureCollection = FeatureCollection.fromFeatures(new Feature[]{Feature.fromGeometry(lineString)});
        Source geoJsonSource = new GeoJsonSource(NAVIGATION_ROUTE_SOURCE, featureCollection);
        mapboxMap.addSource(geoJsonSource);

        LineLayer lineLayer = new LineLayer(NAVIGATION_ROUTE_LAYER, NAVIGATION_ROUTE_SOURCE);
        mapboxMap.removeLayer(lineLayer);

        // The layer properties for our line. This is where we make the line dotted, set the color, etc.
        lineLayer.setProperties(
                //PropertyFactory.lineDasharray(new Float[]{0.01f, 2f}),
                PropertyFactory.lineCap(Property.LINE_CAP_ROUND),
                PropertyFactory.lineJoin(Property.LINE_JOIN_ROUND),
                PropertyFactory.lineWidth(5f),
                PropertyFactory.lineColor(Color.parseColor("#009688"))
        );

        mapboxMap.addLayerBelow(lineLayer, "mapbox-location-accuracy-layer");
```

Is there a smart way to receive the accuracy-layer ID? (or don't you plan to change this ID in the future? ;) )
