### ISSUE TITLE
How to show info window for symbol layer with custom xml layout and handle click events on its views

### ISSUE THREAD

**Issue by mortezahosseinee** [mapbox/mapbox-plugins-android#958]
I use Bubble layout and show custom info window. my info window has EditText, image view and ... . and i need handle click of views on info window that has custom XML layout. bubble layout was deprecated. help me what can i do to do get my goal!!?

i asked same question in another word and i did not get right answer, refer: #649 (comment)

**Comment by mortezahosseinee** [comment]
i see this issue https://github.com/mapbox/mapbox-plugins-android/issues/887 too, but the example in it is deprecated.

**Comment by LukasPaczos** [comment]
This example is not deprecated, it's still the correct way to display a custom bitmap as an InfoWindow. To support your use case, you can try the [MarkerView plugin](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-markerview). Instead of a marker, you can display an info window on top of the symbol layer.

In general, platform views are not supported outside of the MarkerView plugin and custom implementations.
