### ISSUE TITLE
mapBox AnkoComponent

### ISSUE THREAD

**Issue by louaydhyeb** [mapbox/mapbox-plugins-android#967]
Hello everybody , 

How can i use mapBox with ankoComponent and kotlin ? 

Thanks

**Comment by langsmith** [comment]
Hi @louaydhyeb , thanks for looking into Mapbox. 

Tickets in this repo should be about Mapbox plugins specifically, rather than general Mapbox implementation questions. Please send your technical help request to Mapbox via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231 to start a conversation.
